package com.zeroping.vibecheckbe.service;

import com.zeroping.vibecheckbe.dto.PlaylistDTO;
import com.zeroping.vibecheckbe.dto.SongDTO;
import com.zeroping.vibecheckbe.entity.Playlist;
import com.zeroping.vibecheckbe.entity.Song;
import com.zeroping.vibecheckbe.repository.PlaylistRepository;
import jakarta.transaction.Transactional;
import org.springframework.stereotype.Service;

import java.util.HashSet;
import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors;

@Service
public class PlaylistMetadataService {

    private final PlaylistRepository playlistRepository;

    public PlaylistMetadataService(PlaylistRepository playlistRepository) {
        this.playlistRepository = playlistRepository;
    }

    /**
     * Creates and saves the Playlist entity based on the songs found,
     * the playlist name, mood, and the authenticated user ID.
     *
     * @param songs The list of Song entities returned by SpotifyPlaylistService.
     * @param playlistName The name generated by the AI.
     * @param mood The mood from the initial request.
     * @param userId The UUID of the authenticated user.
     * @return The saved Playlist entity.
     */
    @Transactional
    public PlaylistDTO savePlaylistMetadata(
            List<Song> songs,
            String playlistName,
            String mood,
            UUID userId
    ) {
        Playlist playlistEntity = new Playlist();
        playlistEntity.setName(playlistName);
        playlistEntity.setUserId(userId);
        playlistEntity.setMood(mood);
        playlistEntity.setSongs(new HashSet<>(songs));

        playlistEntity = playlistRepository.save(playlistEntity);

        return new PlaylistDTO(
                playlistEntity.getId(),
                playlistEntity.getName(),
                playlistEntity.getMood(),
                playlistEntity.getUserId(),
                playlistEntity.getCreatedAt(),
                songs.stream().map(this::mapToSongDTO).collect(Collectors.toSet())
        );
    }

    public SongDTO mapToSongDTO(Song song) {
        return new SongDTO(
                song.getId(),
                song.getName(),
                song.getUrl(),
                song.getArtist_name()
        );
    }
}
