package com.zeroping.vibecheckbe.service;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import okhttp3.*;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.util.List;

@Service
public class SpotifyService {

    private static final String SPOTIFY_API_BASE = "https://api.spotify.com/v1";
    private final OkHttpClient client = new OkHttpClient();
    private final ObjectMapper mapper = new ObjectMapper();

    public String getCurrentUserId(String accessToken) throws IOException {
        Request request = new Request.Builder()
                .url(SPOTIFY_API_BASE + "/me")
                .header("Authorization", "Bearer " + accessToken)
                .get()
                .build();

        try (Response response = client.newCall(request).execute()) {
            if (!response.isSuccessful()) {
                throw new IOException("Failed to get Spotify user ID: " + response.code());
            }

            String responseBody = response.body().string();
            JsonNode jsonNode = mapper.readTree(responseBody);
            return jsonNode.get("id").asText();
        }
    }

    public String createPlaylist(String accessToken, String spotifyUserId, String playlistName, String description) throws IOException {
        String url = SPOTIFY_API_BASE + "/users/" + spotifyUserId + "/playlists";

        String requestBody = mapper.writeValueAsString(
                mapper.createObjectNode()
                        .put("name", playlistName)
                        .put("description", description != null ? description : "Generated by AI")
                        .put("public", false)
        );

        Request request = new Request.Builder()
                .url(url)
                .header("Authorization", "Bearer " + accessToken)
                .header("Content-Type", "application/json")
                .post(RequestBody.create(requestBody, MediaType.parse("application/json")))
                .build();

        try (Response response = client.newCall(request).execute()) {
            if (!response.isSuccessful()) {
                String errorBody = response.body() != null ? response.body().string() : "";
                throw new IOException("Failed to create Spotify playlist: " + response.code() + " - " + errorBody);
            }

            String responseBody = response.body().string();
            JsonNode jsonNode = mapper.readTree(responseBody);
            return jsonNode.get("id").asText();
        }
    }

    public void addTracksToPlaylist(String accessToken, String spotifyPlaylistId, List<String> trackUris) throws IOException {
        String url = SPOTIFY_API_BASE + "/playlists/" + spotifyPlaylistId + "/tracks";

        String requestBody = mapper.writeValueAsString(
                mapper.createObjectNode()
                        .set("uris", mapper.valueToTree(trackUris))
        );

        Request request = new Request.Builder()
                .url(url)
                .header("Authorization", "Bearer " + accessToken)
                .header("Content-Type", "application/json")
                .post(RequestBody.create(requestBody, MediaType.parse("application/json")))
                .build();

        try (Response response = client.newCall(request).execute()) {
            if (!response.isSuccessful()) {
                String errorBody = response.body() != null ? response.body().string() : "";
                throw new IOException("Failed to add tracks to Spotify playlist: " + response.code() + " - " + errorBody);
            }
        }
    }
}

