package com.zeroping.vibecheckbe.service;

import org.springframework.stereotype.Service;
import org.apache.hc.core5.http.ParseException;
import se.michaelthelin.spotify.SpotifyApi;
import se.michaelthelin.spotify.exceptions.SpotifyWebApiException;
import se.michaelthelin.spotify.model_objects.specification.ArtistSimplified;
import se.michaelthelin.spotify.model_objects.specification.Paging;
import se.michaelthelin.spotify.model_objects.specification.Track;
import se.michaelthelin.spotify.model_objects.specification.User;

import java.io.IOException;
import java.time.Instant;
import java.util.List;
import java.util.Optional;

// Service to interact with Spotify API for searching songs and managing playlists
@Service
public class SpotifyService {
    private final SpotifyApi spotifyApi;

    // Access token + its absolute expiration moment (to refresh before it expires)
    // This is the APP-LEVEL token used for general searching (Client Credentials Flow)
    private String appAccessToken;
    private Instant appTokenExpiresAt;

    public SpotifyService(SpotifyApi spotifyApi) {
        this.spotifyApi = spotifyApi;  // Injected bean from AppConfig (already has clientId & clientSecret)
    }

    public Optional<Track> searchSong(String title, String artist) {
        ensureAppAccessToken(); // Make sure we have a valid app-level token
        spotifyApi.setAccessToken(appAccessToken);

        // Build the query in Spotify's recommended format
        String q = "track: " + title + " artist: " + artist;

        try {
            // Ask for first 10 results
            Paging<Track> page = spotifyApi.searchTracks(q)
                    .limit(10)
                    .build()
                    .execute();

            Track[] items = page.getItems();
            if (items == null || items.length == 0) {
                return Optional.empty();
            }
            for (Track track : items) {
                // Check if the track name contains the title
                boolean titleMatch = track.getName().toLowerCase().contains(title.toLowerCase());

                // Check if any of the artists match
                boolean artistMatch = false;
                for (ArtistSimplified trackArtist : track.getArtists()) {
                    if (trackArtist.getName().toLowerCase().contains(artist.toLowerCase())) {
                        artistMatch = true;
                        break; // Found a match, stop looping artists
                    }
                }

                // If both are a good match, return it
                if (titleMatch && artistMatch) {
                    return Optional.of(track);
                }
            }

            // If looped through all 10 and found no good match, the first one as a fallback
            return Optional.of(items[0]);

        } catch (IOException | SpotifyWebApiException | ParseException e) {
            throw new RuntimeException("Error calling Spotify Search API!", e);
        }
    }

    // Ensure we have a valid app-level access token (Client Credentials Flow)
    private void ensureAppAccessToken() {
        boolean needsRefresh = appAccessToken == null
                || appTokenExpiresAt == null
                || Instant.now().isAfter(appTokenExpiresAt.minusSeconds(60));

        if (needsRefresh) {
            try {
                var creds = spotifyApi.clientCredentials().build().execute();
                this.appAccessToken = creds.getAccessToken();
                this.appTokenExpiresAt = Instant.now().plusSeconds(creds.getExpiresIn());
            } catch (IOException | SpotifyWebApiException | ParseException e) {
                throw new RuntimeException("Failed to obtain Spotify access token.", e);
            }
        }
    }

    // Get the Spotify user ID of the current user
    public String getCurrentUserId(String userAccessToken) {
        spotifyApi.setAccessToken(userAccessToken);
        try {
            User user = spotifyApi.getCurrentUsersProfile().build().execute();
            return user.getId();
        } catch (IOException | SpotifyWebApiException | ParseException e) {
            throw new RuntimeException("Failed to get Spotify user ID", e);
        }
    }

    // Create a new playlist for the user
    public String createPlaylist(String userAccessToken, String spotifyUserId, String playlistName, String description) {
        spotifyApi.setAccessToken(userAccessToken);
        try {
            var playlist = spotifyApi.createPlaylist(spotifyUserId, playlistName)
                    .description(description != null ? description : "Generated by AI")
                    .public_(false) // Default to private
                    .build()
                    .execute();
            return playlist.getId();
        } catch (IOException | SpotifyWebApiException | ParseException e) {
            throw new RuntimeException("Failed to create Spotify playlist", e);
        }
    }

    // Add tracks to an existing playlist
    public void addTracksToPlaylist(String userAccessToken, String spotifyPlaylistId, List<String> trackUris) {
        spotifyApi.setAccessToken(userAccessToken);
        try {
            // Convert List<String> to String[]
            String[] urisArray = trackUris.toArray(new String[0]);

            spotifyApi.addItemsToPlaylist(spotifyPlaylistId, urisArray)
                    .build()
                    .execute();

        } catch (IOException | SpotifyWebApiException | ParseException e) {
            throw new RuntimeException("Failed to add tracks to Spotify playlist", e);
        }
    }
}